config/routes.rb
Rails.application.routes.draw do
  resources :tops
  root 'tops#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IamBach</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="css/top.css">
    <link rel="stylesheet" href="css/responsive.css">
    <!-- <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet"> -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="shortcut icon" href="images/favicon.ico">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag('favicon.ico') %>

  </head>
  <body>
    <ul id="nav">
      <li><%=link_to image_tag("Youtube_icon.png"), 'https://www.youtube.com/user/Mrunitedeveryday?app=desktop', target: :_blank, rel: "noopener noreferrer" %></li>
      <li><%=link_to image_tag("Twitter_logo.png"), 'https://twitter.com/kokakokakolako', target: :_blank, rel: "noopener noreferrer" %></li>
      <li><%=link_to image_tag("instagram.png"), 'https://www.instagram.com/kokakokakolako/', target: :_blank, rel: "noopener noreferrer" %></li>
    </ul>
    <header>
        <%=link_to image_tag("iambh_logo.png"), tops_path %>
        <a href="#Music">Music</a>
        <a href="#Portrait">Portrait</a>
        <a href="#T-shirt">T-shirt</a>
        <a href="#WebApp" class="login">WebApp</a>
        <a href="#Contact" class="login">Contact</a>
      <nav class="sp-nav">
        <ul>
            <li><a href="#Music">Music</a></li>
            <li><a href="#Portrait">Portrait</a></li>
            <li><a href="#T-shirt">T-shirt</a></li>
            <li><a href="#WebApp" class="login">WebApp</a></li>
            <li><a href="#Contact" class="login">Contact</a></li>
            <li class="close"><span>閉じる</span></li>
        </ul>
      </nav>
        <span></span>
    </header>
    <%= yield %>
    <footer>
      <a href="#Music">Music</a>
      <a href="#Portrait">Portrait</a>
      <a href="#T-shirt">T-shirt</a>
      <a href="#WebApp" class="login">WebApp</a>
      <a href="#Contact" class="login">Contact</a>
      <p>©️IamBach2020</p>
    </footer>
  </body>
</html>

app/views/tops/index.html.erb
<body>
  <%= image_tag("top.jpg" , class: "top") %>

  <div id="music">
    <h1>
      Music
    </h1>
    <h3>フォークソング</h3>
        <br>
        <iframe width="560" height="315" src="https://www.youtube.com/embed/I6PhEuBVJoo" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <p class="txt-contents">「えんぴつ」学生の頃に感じてたことを思い出して作りました。</p>
      <%=link_to image_tag("yt_logo_mono_light.png"), 'https://www.youtube.com/user/Mrunitedeveryday/videos?view=0&sort=p&flow=grid', target: :_blank, rel: "noopener noreferrer" %>
  </div>

  <div id="Port">
    <h1>
      Portrait
    </h1>

    <h3>Happy Birthday To Meプロジェクト</h3>
    <p>毎年、誕生日にその年を表す写真を撮りお爺ちゃんになったら個展を開くのが夢です</p>
    <%=link_to image_tag("25portrate.JPG") %>
    <p class="txt-contents">「大きな夢」<br>友達の撮影の手伝いをしていて誕生日が近いからと言って何枚か撮った写真です。この写真の評判が良かったので毎年撮ろうと思いつきました。</p>
    <%=link_to image_tag("26portrate.JPG") %>
    <p class="txt-contents">「令和のニューリーダー」<br>平成から令和へ時代が移り昭和のファッションと平成の象徴を背景に令和を引っ張るリーダーになる。と思いを込めて撮影しました。</p>
    <%=link_to image_tag("27portrate.jpg") %>
    <p class="txt-contents">「守るべきは口元だけですか？」<br>
      マスクでスーツを作りました。
    <%= link_to '【日本赤十字社】「ウイルスの次にやってくるもの」', 'https://youtu.be/rbNuikVDrN4' %>
      という動画からインスピレーションを経て制作しました。一番守るべきは人の心です。</p>
  </div>

  <div id="Tshirt">
    <h1>
      T-shirt
    </h1>
    <h3>ファッションは、アティチュード</h3>
    <p>これは、友人から聞いて納得した言葉です。それなら自分で作ってしまおうということです。</p>
      <%=link_to image_tag("Tochiji.JPG") %>
      <p class="txt-contents">2019年1月バンクシーが日本に作品を残したと噂が広まりました。そんな中、落書きを消すべき行政のトップ自ら記念写真を撮りました。本当にバンクシーの作品だったのかは誰も知りませんが、この一連の騒動をバンクシーは世界のどこかで笑っているかも。</p>
      <%=link_to image_tag("OScace.jpg") %>
      <p class="txt-contents">松居一代さんのYoutubeで登場した"おちんちんシール"とキラキラのラメで愛憎渦巻く現世の男女間を表現しました。</p>
      <%=link_to image_tag("bakuha.JPG") %>
      <p class="txt-contents">たくさんの時間とお金とロマンを爆発という形で終えたロケットは、どんなに辛いことがあっても立ち上がる勇気とチャレンジ精神を学ばせてくれます。</p>
      <%=link_to image_tag("rejibukuro.jpg") %>
      <p class="txt-contents">ポイントカードもってますか？温めますか？お箸いりますか？に加えて新たにレジ係に課された"レジ袋いりますか？"を目で見るだけで唱えなくてもよくすることのできる店員に優しいTシャツ</p>
  </div>
  <div id="message">
    <h2>はちゃめちゃに無茶に世界を信じてる</h2>
    <p>I believe this world in a crazy, reckless way.</p>
  </div>
</body>